### PR TITLE
Add note about expanding on string_measurements

### PR DESCRIPTION
**Pull request by mattster98**
Trying to get this set up for my MGE Pulsar 2200 UPS and ran into some strings not getting quoted, then noticed in the code where it was deciding what to quote and what not to..  seeing this note in advance would have saved me a few minutes! :)  Also realized they need to be sorted.

### CODE REVIEW

**Comment by sa7mon** [comment]
Thanks for your interesting in this tool. I'm not quite sure which strings you're referring to about not getting quoted - do you mean it's not clear that you need to put quotes around the key names in the array on line 5? Also, the keys don't need to be sorted into any order.

**Comment by mattster98** [comment]
Hi - so my UPS outputs a number of strings when I run upsc that weren't already in the string_measurements array, so they didn't get quotes when output into the InfluxDB output.  I had to add them to that array in order to get them quoted.  That's what I'm suggesting adding the note about.

Perhaps I had another typo that was preventing it from working, but even after adding some of the labels to string_measurements, some of the added ones still didn't get quotes in the output.  I assumed the lookup function being used required a sorted set (as many do).  I sorted them and had success, but I may have fixed whatever the original bug was in the process.

**Comment by mattster98** [comment]
Just as a follow-up, I can confirm it is working well (after adding to the string_measurements as explained) on my MGE Pulsar 2200 UPS!

**Comment by openincident** [comment]
Just as a note, I used this command to generate the string measurements line for me. Replace openups with the name of your configured ups:

`upsc openups 2>/dev/null | awk -F':' 'BEGIN {print "string_measurements=["} {print "\"" $1 "\", "} END {print "]"}' |tr -d '\n'`

(note you have to manually remove the last comma from the generated text. Not a big deal for me)

Also, I had to remove the `end=''` line from the last print statement. 

But, it's now up and running with an Openups ups. Thanks.

**Comment by sa7mon** [comment]
Thanks for the feedback from both of you. I'll add the awk command and note about measurements to the readme

**Pull request merged**
